title: Fauzan
email: fncolon@pm.me
description: "My Personal Blog"
baseurl: ""
url: "https://nugraha90.github.io/a-/"
twitter_username: twitter_user
github_username: github_user

# Build settings
# permalink   : /:year/:title/
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

theme: jekyll-theme-cayman
