name: Get total blocknumber of ETH and BTC
on:
  push:
    branches:
      - main

  schedule:
    - cron: "*/10 * * * *"

jobs:
  auto-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          sudo unzip -l assets.zip
          npm install
          node scripts/generate-blocknumber.js
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -am "[AUTO:BUILD] `date`"
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
